# Generated by Django 5.2.10 on 2026-01-28 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('job_type', models.CharField(choices=[('onsite', 'On Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('selection_type', models.CharField(choices=[('test', 'Test'), ('interview', 'Interview'), ('test_interview', 'Test + Interview')], max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('vacancies', models.IntegerField(default=1)),
                ('filled_positions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
